# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://kaz-kobayashi.github.io',
                'git_url': 'https://github.com/kaz-kobayashi/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.mytest': { 'nbdev_hello_world.mytest.foo': ('gis-density.html#foo', 'nbdev_hello_world/mytest.py'),
                                          'nbdev_hello_world.mytest.say_hello': ( 'gis-density.html#say_hello',
                                                                                  'nbdev_hello_world/mytest.py')}}}
