# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://kaz-kobayashi.github.io',
                'git_url': 'https://github.com/kaz-kobayashi/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.mytest': {'nbdev_hello_world.mytest.foo': ('core.html#foo', 'nbdev_hello_world/mytest.py')}}}
