# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_gis-density.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../nbs/01_gis-density.ipynb 6
def foo(): pass

# %% ../nbs/01_gis-density.ipynb 8
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
